import React from "react";
import { NavBar } from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavItemProps } from "@/components/NavItem";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation: NavItemProps[] = [
  {
    name: "Complex form",
    href: "/form",
  },
  {
    name: "Flow builder",
    href: "#",
  },
  {
    name: "Copilot UI",
    href: "#",
  },
];

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar navigation={navigation} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
